/**
 * PMT Phase 2 — customer account system.
 * Additive layer over the existing Google Sheets + Apps Script backend.
 * Routing is wrapped here so the existing Code.gs doGet/doPost remains intact.
 */
const PMT_CUSTOMER_SESSION_SECONDS=21600;
const PMT_CUSTOMER_LOGIN_WINDOW_SECONDS=900;
const PMT_CUSTOMER_MAX_LOGIN_ATTEMPTS=8;
const PMT_CUSTOMER_RESET_SECONDS=1800;
const PMT_CUSTOMER_HASH_ITERATIONS=12000;
const PMT_CUSTOMER_SHEETS={
  identities:'CustomerIdentities',favorites:'Favorites',warranties:'Warranties',customerCoupons:'CustomerCoupons',
  rewards:'RewardsLedger',referrals:'Referrals'
};

function pmtCustomerEnsureSheet_(name,headers){
  let s=S(name);if(!s)s=DB().insertSheet(name);
  if(s.getLastRow()===0)s.getRange(1,1,1,headers.length).setValues([headers]);
  else if(s.getLastColumn()<headers.length){const h=s.getRange(1,1,1,headers.length).getValues()[0];for(let i=0;i<headers.length;i++)if(!h[i])h[i]=headers[i];s.getRange(1,1,1,headers.length).setValues([h]);}
  return s;
}
function pmtCustomerSchema_(){
  pmtCustomerEnsureSheet_('CustomerIdentities',['identity_id','customer_id','provider','email','email_verified','credential_hash','credential_salt','created_at','updated_at','last_login_at','status','verify_hash','verify_expires','recovery_hash','recovery_expires']);
  pmtCustomerEnsureSheet_('Favorites',['favorite_id','customer_id','product_id','created_at']);
  pmtCustomerEnsureSheet_('Warranties',['warranty_id','customer_id','order_id','product','serial_or_reference','start_date','end_date','status','terms','created_at','updated_at']);
  pmtCustomerEnsureSheet_('CustomerCoupons',['claim_id','customer_id','coupon_id','claimed_at','used_at','status']);
  pmtCustomerEnsureSheet_('RewardsLedger',['reward_id','customer_id','type','reference_id','points','description','created_at']);
  pmtCustomerEnsureSheet_('Referrals',['referral_id','referrer_customer_id','referred_customer_id','referral_code','status','reward_reference','created_at','completed_at']);
  const c=S('Customers');if(c){const headers=['id','name','phone','orders','lastActivity','customer_id','email','address','created_at','updated_at'];const h=c.getRange(1,1,1,Math.max(c.getLastColumn(),headers.length)).getValues()[0];for(let i=0;i<headers.length;i++)if(!h[i])h[i]=headers[i];c.getRange(1,1,1,headers.length).setValues([h]);}
  const o=S('Orders');if(o){const h=o.getRange(1,1,1,Math.max(o.getLastColumn(),10)).getValues()[0];if(!h[9])h[9]='customer_id';o.getRange(1,1,1,Math.max(o.getLastColumn(),10)).setValues([h]);}
  const r=S('Repairs');if(r){const h=r.getRange(1,1,1,Math.max(r.getLastColumn(),11)).getValues()[0];if(!h[10])h[10]='customer_id';r.getRange(1,1,1,Math.max(r.getLastColumn(),11)).setValues([h]);}
}
function pmtCustomerBytes_(s){return Utilities.computeHmacSha256Signature(String(s),String(P('PMT_CUSTOMER_PEPPER')||'PMT-CUSTOMER-V1'))}
function pmtCustomerHash_(password,salt){let v=Utilities.base64EncodeWebSafe(pmtCustomerBytes_(String(salt)+'\u0000'+String(password)));for(let i=1;i<PMT_CUSTOMER_HASH_ITERATIONS;i++)v=Utilities.base64EncodeWebSafe(pmtCustomerBytes_(v+'\u0000'+salt));return v.replace(/=+$/,'')}
function pmtCustomerEmail_(v){return String(v||'').trim().toLowerCase()}
function pmtCustomerSafe_(v,max){return clean_(v,max||CFG.MAX_TEXT)}
function pmtCustomerId_(){return 'CUS-'+Utilities.getUuid().replace(/-/g,'').slice(0,16).toUpperCase()}
function pmtCustomerIdentityId_(){return 'CID-'+Utilities.getUuid().replace(/-/g,'').slice(0,16).toUpperCase()}
function pmtCustomerToken_(){return token_()}
function pmtCustomerIdentityByEmail_(email){const s=S('CustomerIdentities');if(!s)return null;const r=s.getDataRange().getValues();const e=pmtCustomerEmail_(email);for(let i=1;i<r.length;i++)if(pmtCustomerEmail_(r[i][3])===e&&String(r[i][2]||'email')==='email')return{sheet:s,row:i+1,data:r[i]};return null}
function pmtCustomerIdentityById_(customerId){const s=S('CustomerIdentities');if(!s)return null;const r=s.getDataRange().getValues();for(let i=1;i<r.length;i++)if(String(r[i][1])===String(customerId))return{sheet:s,row:i+1,data:r[i]};return null}
function pmtCustomerRow_(customerId){const s=S('Customers');if(!s)return null;const r=s.getDataRange().getValues();for(let i=1;i<r.length;i++)if(String(r[i][5]||r[i][0])===String(customerId))return{sheet:s,row:i+1,data:r[i]};return null}
function pmtCustomerSession_(token){if(!token||String(token).length<40)return null;const raw=CacheService.getScriptCache().get('customer_session_'+token);if(!raw)return null;try{const s=JSON.parse(raw);if(!s||!s.customer_id)return null;return s;}catch(e){return null}}
function pmtCustomerSessionCreate_(customerId,identityId){const t=pmtCustomerToken_();CacheService.getScriptCache().put('customer_session_'+t,JSON.stringify({customer_id:String(customerId),identity_id:String(identityId),created_at:new Date().toISOString()}),PMT_CUSTOMER_SESSION_SECONDS);return t}
function pmtCustomerSessionInvalidate_(token){if(token)CacheService.getScriptCache().remove('customer_session_'+token)}
function pmtCustomerAuth_(b){return pmtCustomerSession_(b&&b.customer_token||b&&b.token||'')}
function pmtCustomerResponse_(d){return J(d)}
function pmtCustomerPublicProfile_(customerId){const x=pmtCustomerRow_(customerId);const id=pmtCustomerIdentityById_(customerId);if(!x||!id)return null;return{id:String(x.data[5]||customerId),name:String(x.data[1]||''),phone:String(x.data[2]||''),email:String(x.data[6]||id.data[3]||''),address:String(x.data[7]||'')}}
function pmtCustomerAudit_(event,customerId,meta){try{analyticsEvent_({event:'account_'+event,path:'/account',meta:{customer_id:String(customerId||''),...(meta||{})}})}catch(e){auditSafe_('customer_analytics_error',String(e))}}
function pmtCustomerCreate_(p){
  p=p||{};pmtCustomerSchema_();const email=pmtCustomerEmail_(p.email),password=String(p.password||''),name=pmtCustomerSafe_(p.name,80),phone=pmtCustomerSafe_(p.phone,10),address=pmtCustomerSafe_(p.address,500);
  if(!email_(email)||password.length<10||!name)return pmtCustomerResponse_({ok:false,error:'Invalid signup data',code:'CUSTOMER_SIGNUP_INVALID'});
  if(phone&&!phone_(phone))return pmtCustomerResponse_({ok:false,error:'Invalid phone',code:'CUSTOMER_PHONE_INVALID'});
  if(pmtCustomerIdentityByEmail_(email))return pmtCustomerResponse_({ok:false,error:'An account with this email already exists',code:'CUSTOMER_EMAIL_EXISTS'});
  const lock=LockService.getScriptLock();if(!lock.tryLock(15000))return pmtCustomerResponse_({ok:false,error:'Please retry',code:'CUSTOMER_BUSY'});
  try{
    if(pmtCustomerIdentityByEmail_(email))return pmtCustomerResponse_({ok:false,error:'An account with this email already exists',code:'CUSTOMER_EMAIL_EXISTS'});
    const cid=pmtCustomerId_(),iid=pmtCustomerIdentityId_(),salt=Utilities.getUuid(),hash=pmtCustomerHash_(password,salt),now=now_();
    const cs=S('Customers');if(!cs)throw Error('Customers sheet missing');
    cs.appendRow([cid,name,phone,0,now,cid,email,address,now,now]);
    const is=S('CustomerIdentities');is.appendRow([iid,cid,'email',email,false,hash,salt,now,now,'','Active','','','','']);
    const token=pmtCustomerSessionCreate_(cid,iid);pmtCustomerAudit_('signup',cid);return pmtCustomerResponse_({ok:true,customer:pmtCustomerPublicProfile_(cid),customer_token:token,expiresIn:PMT_CUSTOMER_SESSION_SECONDS,emailVerified:false});
  }catch(e){return pmtCustomerResponse_({ok:false,error:'Could not create account',code:'CUSTOMER_SIGNUP_FAILED'})}finally{lock.releaseLock()}
}
function pmtCustomerLogin_(p){
  p=p||{};pmtCustomerSchema_();const email=pmtCustomerEmail_(p.email),password=String(p.password||'');if(!email_(email)||!password)return pmtCustomerResponse_({ok:false,error:'Invalid credentials',code:'CUSTOMER_LOGIN_INVALID'});
  const key='customer_login_fail_'+Utilities.base64EncodeWebSafe(email).slice(0,80),cache=CacheService.getScriptCache(),attempts=Number(cache.get(key)||0);if(attempts>=PMT_CUSTOMER_MAX_LOGIN_ATTEMPTS)return pmtCustomerResponse_({ok:false,error:'Too many attempts. Try again later.',code:'CUSTOMER_LOGIN_RATE_LIMIT'});
  const found=pmtCustomerIdentityByEmail_(email);if(!found||String(found.data[10]||'Active')!=='Active'||pmtCustomerHash_(password,String(found.data[6]||''))!==String(found.data[5]||'')){cache.put(key,String(attempts+1),PMT_CUSTOMER_LOGIN_WINDOW_SECONDS);return pmtCustomerResponse_({ok:false,error:'Invalid credentials',code:'CUSTOMER_LOGIN_INVALID'})}
  cache.remove(key);const cid=String(found.data[1]),token=pmtCustomerSessionCreate_(cid,String(found.data[0]));found.sheet.getRange(found.row,10).setValue(now_());pmtCustomerAudit_('login',cid);return pmtCustomerResponse_({ok:true,customer:pmtCustomerPublicProfile_(cid),customer_token:token,expiresIn:PMT_CUSTOMER_SESSION_SECONDS,emailVerified:Boolean(found.data[4])});
}
function pmtCustomerLogout_(token){const s=pmtCustomerSession_(token);pmtCustomerSessionInvalidate_(token);if(s)pmtCustomerAudit_('logout',s.customer_id);return pmtCustomerResponse_({ok:true})}
function pmtCustomerRequire_(b){const s=pmtCustomerAuth_(b);if(!s)throw Error('Unauthorized');return s}
function pmtCustomerProfile_(s){return pmtCustomerResponse_({ok:true,customer:pmtCustomerPublicProfile_(s.customer_id)})}
function pmtCustomerProfileUpdate_(s,p){p=p||{};const c=pmtCustomerRow_(s.customer_id);if(!c)return pmtCustomerResponse_({ok:false,error:'Customer not found'});const email=pmtCustomerEmail_(p.email||'');if(email&&!email_(email))return pmtCustomerResponse_({ok:false,error:'Invalid email'});if(p.phone&&!phone_(String(p.phone)))return pmtCustomerResponse_({ok:false,error:'Invalid phone'});if(email){const other=pmtCustomerIdentityByEmail_(email);if(other&&String(other.data[1])!==String(s.customer_id))return pmtCustomerResponse_({ok:false,error:'Email already in use'});}
  const name=p.name!=null?pmtCustomerSafe_(p.name,80):String(c.data[1]||''),phone=p.phone!=null?pmtCustomerSafe_(p.phone,10):String(c.data[2]||''),address=p.address!=null?pmtCustomerSafe_(p.address,500):String(c.data[7]||'');c.sheet.getRange(c.row,2).setValue(name);c.sheet.getRange(c.row,3).setValue(phone);c.sheet.getRange(c.row,7).setValue(email||String(c.data[6]||''));c.sheet.getRange(c.row,8).setValue(address);c.sheet.getRange(c.row,10).setValue(now_());if(email){const id=pmtCustomerIdentityById_(s.customer_id);if(id)id.sheet.getRange(id.row,4).setValue(email)}pmtCustomerAudit_('profile_update',s.customer_id);return pmtCustomerResponse_({ok:true,customer:pmtCustomerPublicProfile_(s.customer_id)})}
function pmtCustomerOrders_(s){const sh=S('Orders');if(!sh)return pmtCustomerResponse_({ok:true,data:[]});const h=sh.getRange(1,1,1,Math.max(10,sh.getLastColumn())).getValues()[0],cid=h.indexOf('customer_id');if(cid<0)return pmtCustomerResponse_({ok:true,data:[]});const r=sh.getDataRange().getValues(),out=[];for(let i=1;i<r.length;i++)if(String(r[i][cid])===String(s.customer_id)){let items=[];try{items=JSON.parse(String(r[i][4]||'[]'))}catch(e){}out.push({id:String(r[i][0]),date:String(r[i][1]),items,total:Number(r[i][5]||0),payment:String(r[i][6]||''),status:String(r[i][7]||'Pending')})}pmtCustomerAudit_('order_history_view',s.customer_id);return pmtCustomerResponse_({ok:true,data:out.reverse()})}
function pmtCustomerRepairs_(s){const sh=S('Repairs');if(!sh)return pmtCustomerResponse_({ok:true,data:[]});const h=sh.getRange(1,1,1,Math.max(11,sh.getLastColumn())).getValues()[0],cid=h.indexOf('customer_id');if(cid<0)return pmtCustomerResponse_({ok:true,data:[]});const r=sh.getDataRange().getValues(),out=[];for(let i=1;i<r.length;i++)if(String(r[i][cid])===String(s.customer_id))out.push({id:String(r[i][0]),date:String(r[i][1]),device:String(r[i][4]||''),issue:String(r[i][5]||''),status:String(r[i][7]||'Pending'),estimate:Number(r[i][8]||0),updated:String(r[i][9]||r[i][1]||'')});pmtCustomerAudit_('repair_history_view',s.customer_id);return pmtCustomerResponse_({ok:true,data:out.reverse()})}
function pmtCustomerWarranties_(s){const sh=S('Warranties');if(!sh)return pmtCustomerResponse_({ok:true,data:[]});const r=sh.getDataRange().getValues(),out=[];for(let i=1;i<r.length;i++)if(String(r[i][1])===String(s.customer_id))out.push({id:String(r[i][0]),orderId:String(r[i][2]),product:String(r[i][3]),reference:String(r[i][4]),startDate:String(r[i][5]),endDate:String(r[i][6]),status:String(r[i][7]),terms:String(r[i][8])});pmtCustomerAudit_('warranty_view',s.customer_id);return pmtCustomerResponse_({ok:true,data:out.reverse()})}
function pmtCustomerFavorites_(s){const sh=S('Favorites');if(!sh)return pmtCustomerResponse_({ok:true,data:[]});const products=productRows_(),map={};products.forEach(p=>map[p.id]=p);const r=sh.getDataRange().getValues(),out=[];for(let i=1;i<r.length;i++)if(String(r[i][1])===String(s.customer_id)){const p=map[String(r[i][2])];if(p)out.push({id:String(r[i][0]),productId:p.id,name:p.name,price:p.price,stock:p.stock,images:p.images,category:p.category})}return pmtCustomerResponse_({ok:true,data:out.reverse()})}
function pmtCustomerFavorite_(s,p,remove){p=p||{};const pid=pmtCustomerSafe_(p.product_id,120),ps=S('Products');if(!pid||!ps)return pmtCustomerResponse_({ok:false,error:'Product not found'});const pr=productRows_().find(x=>String(x.id)===pid);if(!pr||pr.status==='Archived'||pr.deletedAt)return pmtCustomerResponse_({ok:false,error:'Product not found'});const sh=S('Favorites');const r=sh.getDataRange().getValues();let found=-1;for(let i=1;i<r.length;i++)if(String(r[i][1])===String(s.customer_id)&&String(r[i][2])===pid){found=i+1;break}if(remove){if(found>0)sh.deleteRow(found);pmtCustomerAudit_('favorite_remove',s.customer_id,{product_id:pid});return pmtCustomerResponse_({ok:true})}if(found<0)sh.appendRow(['FAV-'+Utilities.getUuid().slice(0,12).toUpperCase(),s.customer_id,pid,now_()]);pmtCustomerAudit_('favorite_add',s.customer_id,{product_id:pid});return pmtCustomerResponse_({ok:true})}
function pmtCustomerCoupons_(s){const sh=S('CustomerCoupons'),r=sh.getDataRange().getValues(),coupons=coupons_();let items=[];try{items=JSON.parse(coupons.getContent())?.data||[]}catch(e){}const out=[];for(let i=1;i<r.length;i++)if(String(r[i][1])===String(s.customer_id))out.push({claimId:String(r[i][0]),couponId:String(r[i][2]),claimedAt:String(r[i][3]),usedAt:String(r[i][4]||''),status:String(r[i][5]||'Claimed'),coupon:items.find(x=>String(x.id)===String(r[i][2]))||null});return pmtCustomerResponse_({ok:true,data:out})}
function pmtCustomerClaimCoupon_(s,p){const couponId=pmtCustomerSafe_(p&&p.coupon_id,120);const all=coupons_();let list=[];try{list=JSON.parse(all.getContent())?.data||[]}catch(e){}const coupon=list.find(x=>String(x.id)===couponId||String(x.code).toUpperCase()===String(couponId).toUpperCase());if(!coupon||!coupon.active)return pmtCustomerResponse_({ok:false,error:'Coupon is not available'});const sh=S('CustomerCoupons'),r=sh.getDataRange().getValues();for(let i=1;i<r.length;i++)if(String(r[i][1])===String(s.customer_id)&&String(r[i][2])===String(coupon.id)&&String(r[i][5]||'Claimed')!=='Used')return pmtCustomerResponse_({ok:false,error:'Coupon already claimed',code:'COUPON_ALREADY_CLAIMED'});sh.appendRow(['CC-'+Utilities.getUuid().slice(0,12).toUpperCase(),s.customer_id,coupon.id,now_(),'','Claimed']);pmtCustomerAudit_('coupon_claim',s.customer_id,{coupon_id:coupon.id});return pmtCustomerResponse_({ok:true,coupon})}
function pmtCustomerRewards_(s){const sh=S('RewardsLedger');const r=sh.getDataRange().getValues(),out=[];let balance=0;for(let i=1;i<r.length;i++)if(String(r[i][1])===String(s.customer_id)){const pts=Number(r[i][4]||0);balance+=pts;out.push({id:String(r[i][0]),type:String(r[i][2]),referenceId:String(r[i][3]),points:pts,description:String(r[i][5]),createdAt:String(r[i][6])})}pmtCustomerAudit_('reward_view',s.customer_id);return pmtCustomerResponse_({ok:true,balance,ledger:out.reverse()})}
function pmtCustomerReferral_(s,p){const code=pmtCustomerSafe_(p&&p.referral_code,40).toUpperCase();if(!code)return pmtCustomerResponse_({ok:false,error:'Referral code is required'});const sh=S('Referrals'),r=sh.getDataRange().getValues();let found=null;for(let i=1;i<r.length;i++)if(String(r[i][3]).toUpperCase()===code){found=r[i];break}if(!found)return pmtCustomerResponse_({ok:false,error:'Referral code not found'});if(String(found[1])===String(s.customer_id))return pmtCustomerResponse_({ok:false,error:'Self-referral is not allowed'});for(let i=1;i<r.length;i++)if(String(r[i][2])===String(s.customer_id))return pmtCustomerResponse_({ok:false,error:'This account already has a referral'});const id='REF-'+Utilities.getUuid().slice(0,12).toUpperCase();sh.appendRow([id,found[1],s.customer_id,code,'Pending','',now_(),'']);pmtCustomerAudit_('referral_created',s.customer_id);return pmtCustomerResponse_({ok:true,referralId:id,status:'Pending'})}
function pmtCustomerReferrals_(s){const sh=S('Referrals'),r=sh.getDataRange().getValues(),out=[];for(let i=1;i<r.length;i++)if(String(r[i][1])===String(s.customer_id)||String(r[i][2])===String(s.customer_id))out.push({id:String(r[i][0]),referrerId:String(r[i][1]),referredId:String(r[i][2]),code:String(r[i][3]),status:String(r[i][4]),createdAt:String(r[i][6]),completedAt:String(r[i][7]||'')});return pmtCustomerResponse_({ok:true,data:out.reverse()})}
function pmtCustomerCreateReferralCode_(s){const sh=S('Referrals'),r=sh.getDataRange().getValues();for(let i=1;i<r.length;i++)if(String(r[i][1])===String(s.customer_id)&&String(r[i][3]))return pmtCustomerResponse_({ok:true,referralCode:String(r[i][3])});const code=('PMT'+String(s.customer_id).replace(/[^A-Z0-9]/gi,'').slice(-8)+Math.random().toString(36).slice(2,7)).toUpperCase();sh.appendRow(['REF-'+Utilities.getUuid().slice(0,12).toUpperCase(),s.customer_id,'',code,'CodeIssued','',now_(),'']);return pmtCustomerResponse_({ok:true,referralCode:code})}
function pmtCustomerReorder_(s,p){const orderId=pmtCustomerSafe_(p&&p.order_id,120),sh=S('Orders');if(!orderId||!sh)return pmtCustomerResponse_({ok:false,error:'Order not found'});const h=sh.getRange(1,1,1,Math.max(10,sh.getLastColumn())).getValues()[0],cid=h.indexOf('customer_id');if(cid<0)return pmtCustomerResponse_({ok:false,error:'Order is not linked to this account'});const r=sh.getDataRange().getValues();let row=null;for(let i=1;i<r.length;i++)if(String(r[i][0])===orderId&&String(r[i][cid])===String(s.customer_id)){row=r[i];break}if(!row)return pmtCustomerResponse_({ok:false,error:'Order not found'});let old=[];try{old=JSON.parse(String(row[4]||'[]'))}catch(e){}const products=productRows_(),map={};products.forEach(x=>map[x.id]=x);const available=[],unavailable=[];old.forEach(it=>{const p=map[String(it.id)],q=Math.max(1,Math.min(99,Number(it.qty)||1));if(!p||p.status==='Archived'||p.deletedAt||Number(p.stock||0)<=0)unavailable.push({id:String(it.id),name:String(it.name||it.id),reason:'Unavailable'});else{const v=(p.variants||[]).find(x=>String(x.id)===String(it.variantId||''));if(it.variantId&&(!v||Number(v.stock||0)<=0))unavailable.push({id:String(it.id),name:p.name,reason:'Variant unavailable'});else available.push({id:p.id,name:p.name,variantId:v?String(v.id):'',price:Number(v?.price??p.price??0),qty:Math.min(q,Math.max(1,Number(v?.stock??p.stock??0)))})}});pmtCustomerAudit_('reorder_start',s.customer_id,{order_id:orderId});return pmtCustomerResponse_({ok:true,orderId,available,unavailable})}
function pmtCustomerRecoveryRequest_(p){const email=pmtCustomerEmail_(p&&p.email);if(!email_(email))return pmtCustomerResponse_({ok:true,message:'If the account exists, recovery instructions have been sent.'});const found=pmtCustomerIdentityByEmail_(email);if(!found)return pmtCustomerResponse_({ok:true,message:'If the account exists, recovery instructions have been sent.'});const raw=pmtCustomerToken_(),hash=sha_(raw),exp=new Date(Date.now()+PMT_CUSTOMER_RESET_SECONDS*1000);found.sheet.getRange(found.row,14).setValue(hash);found.sheet.getRange(found.row,15).setValue(exp);const base=ScriptApp.getService().getUrl()||P('PMT_PUBLIC_SITE_URL')||'https://piyare-mobile-telecom.sadab-notes-backup.workers.dev';const link=base+'/reset-password.html?token='+encodeURIComponent(raw);const emailTo=email;try{MailApp.sendEmail({to:emailTo,subject:'Piyare Mobile Telecom account recovery',htmlBody:'Use this link to reset your password. It expires in 30 minutes:<br><br><a href="'+htmlEscape_(link)+'">Reset password</a>'})}catch(e){auditSafe_('customer_recovery_email_error',String(e))}return pmtCustomerResponse_({ok:true,message:'If the account exists, recovery instructions have been sent.'})}
function pmtCustomerResetPassword_(p){const raw=pmtCustomerSafe_(p&&p.token,200),password=String(p&&p.password||'');if(raw.length<40||password.length<10)return pmtCustomerResponse_({ok:false,error:'Invalid reset request',code:'CUSTOMER_RESET_INVALID'});const sh=S('CustomerIdentities'),r=sh.getDataRange().getValues(),hash=sha_(raw);for(let i=1;i<r.length;i++)if(String(r[i][13])===hash&&new Date(r[i][14]).getTime()>Date.now()){const salt=Utilities.getUuid(),newHash=pmtCustomerHash_(password,salt);sh.getRange(i+1,6).setValue(newHash);sh.getRange(i+1,7).setValue(salt);sh.getRange(i+1,14).setValue('');sh.getRange(i+1,15).setValue('');const cid=String(r[i][1]);pmtCustomerAudit_('recovery',cid);return pmtCustomerResponse_({ok:true,message:'Password updated. Please sign in again.'})}return pmtCustomerResponse_({ok:false,error:'Reset link is invalid or expired',code:'CUSTOMER_RESET_EXPIRED'})}
function pmtCustomerVerifyEmail_(p){const raw=pmtCustomerSafe_(p&&p.token,200);if(!raw)return pmtCustomerResponse_({ok:false,error:'Invalid verification link'});const sh=S('CustomerIdentities'),r=sh.getDataRange().getValues(),hash=sha_(raw);for(let i=1;i<r.length;i++)if(String(r[i][11])===hash&&new Date(r[i][12]).getTime()>Date.now()){sh.getRange(i+1,5).setValue(true);sh.getRange(i+1,12).setValue('');sh.getRange(i+1,13).setValue('');return pmtCustomerResponse_({ok:true,message:'Email verified'})}return pmtCustomerResponse_({ok:false,error:'Verification link is invalid or expired'})}
function pmtCustomerLinkExisting_(customerId,fieldName,identifier){const c=pmtCustomerRow_(customerId);if(!c)return;const sh=S(fieldName==='Orders'?'Orders':'Repairs');if(!sh)return;const h=sh.getRange(1,1,1,Math.max(fieldName==='Orders'?10:11,sh.getLastColumn())).getValues()[0],idx=h.indexOf('customer_id');if(idx<0)return;const phoneIdx=fieldName==='Orders'?3:3;const r=sh.getDataRange().getValues();for(let i=1;i<r.length;i++)if(String(r[i][0])===String(identifier)&&!String(r[i][idx])){sh.getRange(i+1,idx+1).setValue(customerId);return}}
function pmtCustomerAttachCreated_(customerId,kind,id){try{pmtCustomerSchema_();pmtCustomerLinkExisting_(customerId,kind,id);if(kind==='Orders'){const c=pmtCustomerRow_(customerId);if(c){c.sheet.getRange(c.row,4).setValue(Number(c.data[3]||0)+1);c.sheet.getRange(c.row,5).setValue(now_());c.sheet.getRange(c.row,10).setValue(now_())}}}catch(e){auditSafe_('customer_link_error',String(e))}}
function pmtCustomerAdminDetail_(p,session){if(!session||!roleAllowed_(session,'Support'))return forbidden_();const id=pmtCustomerSafe_(p&&p.id,120),c=pmtCustomerRow_(id);if(!c)return J({ok:false,message:'Customer not found'});const profile=pmtCustomerPublicProfile_(id);const orders=pmtCustomerOrders_({customer_id:id});const repairs=pmtCustomerRepairs_({customer_id:id});let od=[],rd=[];try{od=JSON.parse(orders.getContent())?.data||[]}catch(e){}try{rd=JSON.parse(repairs.getContent())?.data||[]}catch(e){}return J({ok:true,customer:profile,orders:od,repairs:rd,warranties:JSON.parse(pmtCustomerWarranties_({customer_id:id}).getContent())?.data||[],rewards:JSON.parse(pmtCustomerRewards_({customer_id:id}).getContent())||{balance:0,ledger:[]},referrals:JSON.parse(pmtCustomerReferrals_({customer_id:id}).getContent())?.data||[]})}

/* ----- wrapper: this is the single effective customer-aware router ----- */
var PMT_PREV_CUSTOMER_DOGET=doGet;
var PMT_PREV_CUSTOMER_DOPOST=doPost;
doGet=function(e){
  try{
    const p=(e&&e.parameter)||{},a=clean_(p.action,80),s=pmtCustomerSession_(p.customer_token||p.token||'');
    if(a==='customerProfile')return s?pmtCustomerProfile_(s):forbidden_();
    if(a==='customerOrders')return s?pmtCustomerOrders_(s):forbidden_();
    if(a==='customerRepairs')return s?pmtCustomerRepairs_(s):forbidden_();
    if(a==='customerWarranties')return s?pmtCustomerWarranties_(s):forbidden_();
    if(a==='customerFavorites')return s?pmtCustomerFavorites_(s):forbidden_();
    if(a==='customerCoupons')return s?pmtCustomerCoupons_(s):forbidden_();
    if(a==='customerRewards')return s?pmtCustomerRewards_(s):forbidden_();
    if(a==='customerReferrals')return s?pmtCustomerReferrals_(s):forbidden_();
    if(a==='customerAdminDetail')return pmtCustomerAdminDetail_(p,auth_(p.token));
    return PMT_PREV_CUSTOMER_DOGET(e);
  }catch(err){return J({ok:false,error:String(err&&err.message||err),code:'CUSTOMER_ROUTE_ERROR'})}
};
doPost=function(e){
  let b={};try{b=JSON.parse((e&&e.postData&&e.postData.contents)||'{}')}catch(err){return J({ok:false,error:'Invalid request',code:'INVALID_JSON'})}
  const a=clean_(b.action,80),token=String(b.customer_token||b.token||''),s=pmtCustomerSession_(token);
  try{
    if(a==='customerSignup')return pmtCustomerCreate_(b.payload||{});
    if(a==='customerLogin')return pmtCustomerLogin_(b.payload||{});
    if(a==='customerLogout')return pmtCustomerLogout_(token);
    if(a==='customerRecoveryRequest')return pmtCustomerRecoveryRequest_(b.payload||{});
    if(a==='customerResetPassword')return pmtCustomerResetPassword_(b.payload||{});
    if(a==='customerVerifyEmail')return pmtCustomerVerifyEmail_(b.payload||{});
    if(a==='customerProfileUpdate')return s?pmtCustomerProfileUpdate_(s,b.payload||{}):forbidden_();
    if(a==='customerFavoriteAdd')return s?pmtCustomerFavorite_(s,b.payload||{},false):forbidden_();
    if(a==='customerFavoriteRemove')return s?pmtCustomerFavorite_(s,b.payload||{},true):forbidden_();
    if(a==='customerClaimCoupon')return s?pmtCustomerClaimCoupon_(s,b.payload||{}):forbidden_();
    if(a==='customerReferralCode')return s?pmtCustomerCreateReferralCode_(s):forbidden_();
    if(a==='customerReferralCreate')return s?pmtCustomerReferral_(s,b.payload||{}):forbidden_();
    if(a==='customerReorder')return s?pmtCustomerReorder_(s,b.payload||{}):forbidden_();
    if(a==='customerGrantReward')return (function(){if(!auth_(b.token)||!roleAllowed_(auth_(b.token),'Owner'))return forbidden_();const p=b.payload||{},cid=pmtCustomerSafe_(p.customer_id,120),pts=Math.round(Number(p.points)||0);if(!cid||!pts)return J({ok:false,error:'Invalid reward'});const sh=S('RewardsLedger');sh.appendRow(['RWD-'+Utilities.getUuid().slice(0,12).toUpperCase(),cid,p.type||'ADMIN_ADJUSTMENT',p.reference_id||'',pts,p.description||'Admin adjustment',now_()]);return J({ok:true})})();
    if(a==='createOrder'&&s){const out=PMT_PREV_CUSTOMER_DOPOST(e);try{const d=JSON.parse(out.getContent());if(d&&d.ok&&d.id)pmtCustomerAttachCreated_(s.customer_id,'Orders',d.id)}catch(x){}return out;}
    if(a==='createRepair'&&s){const out=PMT_PREV_CUSTOMER_DOPOST(e);try{const d=JSON.parse(out.getContent());if(d&&d.ok&&d.ticket)pmtCustomerAttachCreated_(s.customer_id,'Repairs',d.ticket)}catch(x){}return out;}
    return PMT_PREV_CUSTOMER_DOPOST(e);
  }catch(err){return J({ok:false,error:String(err&&err.message||err),code:err&&err.message==='Unauthorized'?'UNAUTHORIZED':'CUSTOMER_ROUTE_ERROR'})}
};

/* One-time additive migration. Safe to call repeatedly. */
function migrateCustomerAccounts(){pmtCustomerSchema_();const cs=S('Customers');if(!cs)return 'Customers sheet missing';const r=cs.getDataRange().getValues();for(let i=1;i<r.length;i++){const row=i+1,existing=String(r[i][5]||'').trim(),legacy=String(r[i][0]||'').trim();if(!existing){const cid=legacy&&/^CUS-/.test(legacy)?legacy:pmtCustomerId_();cs.getRange(row,6).setValue(cid);cs.getRange(row,9).setValue(r[i][4]||now_());cs.getRange(row,10).setValue(now_())}}
  const o=S('Orders');if(o){const h=o.getRange(1,1,1,Math.max(10,o.getLastColumn())).getValues()[0],idx=h.indexOf('customer_id'),phoneIdx=h.indexOf('phone'),nameIdx=h.indexOf('customer');if(idx>=0&&phoneIdx>=0){const cr=cs.getDataRange().getValues(),byPhone={};for(let i=1;i<cr.length;i++){const ph=String(cr[i][2]||'');if(ph&&!byPhone[ph])byPhone[ph]=String(cr[i][5]||'')}const rr=o.getDataRange().getValues();for(let i=1;i<rr.length;i++)if(!String(rr[i][idx])&&byPhone[String(rr[i][phoneIdx]||'')])o.getRange(i+1,idx+1).setValue(byPhone[String(rr[i][phoneIdx]||'')])}}
  const rep=S('Repairs');if(rep){const h=rep.getRange(1,1,1,Math.max(11,rep.getLastColumn())).getValues()[0],idx=h.indexOf('customer_id'),phoneIdx=h.indexOf('phone');if(idx>=0&&phoneIdx>=0){const cr=cs.getDataRange().getValues(),byPhone={};for(let i=1;i<cr.length;i++){const ph=String(cr[i][2]||'');if(ph&&!byPhone[ph])byPhone[ph]=String(cr[i][5]||'')}const rr=rep.getDataRange().getValues();for(let i=1;i<rr.length;i++)if(!String(rr[i][idx])&&byPhone[String(rr[i][phoneIdx]||'')])rep.getRange(i+1,idx+1).setValue(byPhone[String(rr[i][phoneIdx]||'')])}}
  return 'Customer account schema migration complete.';
}
