package com.piyare.mobiletelecom.smsbridge;

import android.app.Activity;import android.content.Intent;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.os.Bundle;import android.view.Gravity;import android.webkit.CookieManager;import android.webkit.PermissionRequest;import android.webkit.ValueCallback;import android.webkit.WebChromeClient;import android.webkit.WebResourceRequest;import android.webkit.WebSettings;import android.webkit.WebView;import android.webkit.WebViewClient;import android.widget.Button;import android.widget.FrameLayout;import android.widget.LinearLayout;import android.widget.TextView;

public class AdminActivity extends Activity {
 private static final String ADMIN_URL="https://piyare-mobile-telecom.sadab-notes-backup.workers.dev/admin/",BILLING_URL="https://piyare-mobile-telecom.sadab-notes-backup.workers.dev/admin/billing.html",API="https://piyare-mobile-telecom.sadab-notes-backup.workers.dev/api";private static final int FILE_PICKER=701;private WebView web;private ValueCallback<Uri[]> uploadCallback;private int dp(float n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
 private String theme(){return getSharedPreferences("app_theme",MODE_PRIVATE).getString("theme","classic");}
 private GradientDrawable rounded(int color,float r){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(r));return g;}
 private Button button(String glyph,String label){Button b=new Button(this);b.setText(glyph);b.setContentDescription(label);b.setTextSize(19);b.setTextColor(0xFFFFFFFF);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setPadding(0,0,0,0);b.setBackground(rounded(theme().equals("blueprint")?0xFF0B3558:theme().equals("paper")?0xFF2F2A20:0xFF242A3A,13));return b;}
 private void applyWebTheme(){if(web==null)return;String t=theme();if("classic".equals(t)){web.evaluateJavascript("document.documentElement.removeAttribute('data-apk-theme');document.getElementById('pmt-apk-theme')?.remove();",null);return;}String css="*{transition:background-color .15s ease,color .15s ease,border-color .15s ease!important}body{background:"+("paper".equals(t)?"#F4F1E8":"#EBF2FA")+"!important;color:"+("paper".equals(t)?"#302B22":"#0C2D4E")+"!important}header,.admin-top,.admin-nav{background:"+("paper".equals(t)?"#2F2A20":"#0B3558")+"!important}.panel,.cms-section,.card,.form-card,.table-wrap,.admin-card{background:"+("paper".equals(t)?"#FFFDF5":"#F8FBFF")+"!important;border-color:"+("paper".equals(t)?"#D8CFBD":"#B8CCE0")+"!important}.btn-blue{background:"+("paper".equals(t)?"#315C9B":"#0B5CAD")+"!important}.admin-main,.admin-wrap{background:transparent!important}";String js="(function(){var old=document.getElementById('pmt-apk-theme');if(old)old.remove();var s=document.createElement('style');s.id='pmt-apk-theme';s.textContent="+org.json.JSONObject.quote(css)+";document.head.appendChild(s);document.documentElement.setAttribute('data-apk-theme','"+t+"');})();";web.evaluateJavascript(js,null);}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(theme().equals("blueprint")?0xFF0B3558:theme().equals("paper")?0xFF2F2A20:0xFF111827);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(6),dp(5),dp(6),dp(5));bar.setBackgroundColor(theme().equals("blueprint")?0xFF0B3558:theme().equals("paper")?0xFF2F2A20:0xFF111827);Button home=button("⌂","Home");home.setOnClickListener(v->goHome());bar.addView(home,new LinearLayout.LayoutParams(dp(48),dp(46)));Button back=button("‹","Back");back.setOnClickListener(v->{if(web.canGoBack())web.goBack();else goHome();});LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(dp(48),dp(46));bp.leftMargin=dp(6);bar.addView(back,bp);TextView title=new TextView(this);title.setText("PMT Admin Control");title.setTextColor(0xFFFFFFFF);title.setTextSize(15);title.setTypeface(null,android.graphics.Typeface.BOLD);title.setGravity(Gravity.CENTER);bar.addView(title,new LinearLayout.LayoutParams(0,dp(46),1));Button logout=button("⇥","Logout");logout.setOnClickListener(v->logout());LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(48),dp(46));lp.leftMargin=dp(6);bar.addView(logout,lp);root.addView(bar);FrameLayout frame=new FrameLayout(this);web=new WebView(this);frame.addView(web,new FrameLayout.LayoutParams(-1,-1));root.addView(frame,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);
  WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setDatabaseEnabled(true);s.setAllowFileAccess(true);s.setAllowContentAccess(true);s.setBuiltInZoomControls(false);s.setDisplayZoomControls(false);s.setLoadWithOverviewMode(false);s.setUseWideViewPort(false);s.setMediaPlaybackRequiresUserGesture(false);s.setSupportZoom(false);CookieManager.getInstance().setAcceptCookie(true);CookieManager.getInstance().setAcceptThirdPartyCookies(web,true);
  web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){Uri u=r.getUrl();String host=u.getHost();if(host!=null&&host.equals("piyare-mobile-telecom.sadab-notes-backup.workers.dev"))return false;try{startActivity(new Intent(Intent.ACTION_VIEW,u));}catch(Exception ignored){}return true;}@Override public void onPageFinished(WebView v,String url){super.onPageFinished(v,url);applyWebTheme();}});
  web.setWebChromeClient(new WebChromeClient(){@Override public void onPermissionRequest(final PermissionRequest request){runOnUiThread(()->{String[] wanted=request.getResources();for(String r:wanted){if(PermissionRequest.RESOURCE_VIDEO_CAPTURE.equals(r)){if(checkSelfPermission(android.Manifest.permission.CAMERA)==android.content.pm.PackageManager.PERMISSION_GRANTED){request.grant(new String[]{PermissionRequest.RESOURCE_VIDEO_CAPTURE});return;}requestPermissions(new String[]{android.Manifest.permission.CAMERA},902);return;}}request.deny();});}@Override public boolean onShowFileChooser(WebView v,ValueCallback<Uri[]> cb,FileChooserParams params){if(uploadCallback!=null)uploadCallback.onReceiveValue(null);uploadCallback=cb;try{Intent i=params.createIntent();i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,FILE_PICKER);return true;}catch(Exception e){uploadCallback=null;return false;}}});
  boolean billing=b!=null&&b.getBoolean("openBilling",false);web.loadUrl(billing?BILLING_URL:ADMIN_URL);
 }
 private void goHome(){startActivity(new Intent(this,HomeActivity.class).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP));finish();}
 private void logout(){web.evaluateJavascript("(async()=>{try{const t=sessionStorage.getItem('pmt-admin-token');await fetch('"+API+"',{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'logout',token:t||''})});}catch(e){}sessionStorage.clear();localStorage.removeItem('pmt-admin-token');localStorage.removeItem('pmt-admin-user');})()",v->goHome());}
 @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode==FILE_PICKER&&uploadCallback!=null){Uri[] r=null;if(resultCode==RESULT_OK&&data!=null){Uri u=data.getData();if(u!=null)r=new Uri[]{u};else if(data.getClipData()!=null){int n=data.getClipData().getItemCount();r=new Uri[n];for(int i=0;i<n;i++)r[i]=data.getClipData().getItemAt(i).getUri();}}uploadCallback.onReceiveValue(r);uploadCallback=null;}}
 @Override public void onRequestPermissionsResult(int requestCode,String[] permissions,int[] grants){super.onRequestPermissionsResult(requestCode,permissions,grants);if(requestCode==902&&grants.length>0&&grants[0]==android.content.pm.PackageManager.PERMISSION_GRANTED&&web!=null)web.reload();}
 @Override public void onBackPressed(){if(web!=null&&web.canGoBack())web.goBack();else goHome();}@Override protected void onDestroy(){if(uploadCallback!=null){uploadCallback.onReceiveValue(null);uploadCallback=null;}if(web!=null){web.stopLoading();web.destroy();}super.onDestroy();}
}
